### ISSUE TITLE
Fix Memory Leak

### ISSUE THREAD

**Issue by gabrielfelipeg** [DiegoGamaV/NedeReural#31]

**Comment by mvilkin** [comment]
Seems interestinag. Can you add some more info?

**Comment by DiegoGamaV** [comment]
Well, what is happening is that when we start to train the network, the memory usage goes up to around 30% (in a laptop of around 8 GB of RAM). After that, in each training epoch it also grows a little, making it harder for us to train more then 5 epochs per training session. 
At the start of the training, we load the training examples with the MNIST dataset and we also load the network with the saved weights and biases from previous trainings. We believe that most of the Memory Leak is around this period, but because of the gradient increase of memory within the epochs, we also think that there are Leaks in this part. The hard part is that we don't know exactly where the Leak is.

**Comment by noshbar** [comment]
I just had a quick look at the code, so sorry if I'm missing anything, but:
doriNum.cpp - the Narray class should probably free the doubles in the (non-existent) destructor, correct?

Also, make sure not just to free the values[i] elements individually, but the whole values array, too (so free(values) as well).

Good luck!

**Comment by gabrielfelipeg** [comment]
We tried create close() method like as destructor and call then in all other structs in [this commit](https://github.com/DiegoGamaV/NedeReural/commit/4fcce81a2c523eebc99287f4324783b31748349d), but the memory consume only increased.

**Comment by bvwells** [comment]
Probably worth running the application through Valgrind (http://valgrind.org). I'm sure this will quickly spot any memory leaks. Hope this helps!

**Comment by gabrielfelipeg** [comment]
#33  solving this
